name: Hitting the cronjob endpoint every day at 18:00 UTC(23:30 IST) to update db and meilisearch

on:
  schedule:
    - cron: "0 18 * * *"
jobs:
  build:
    name: Send a GET request via wget
    runs-on: ubuntu-latest
    steps:
      - name: wget request
        run: wget https://api.mike.chiraghosh.me/script