name: Hitting the cronjob endpoint every day at 19:00 UTC(00:30 IST) to send mails about upcoming hearings

on:
  schedule:
    - cron: "0 19 * * *"
jobs:
  build:
    name: Send a GET request via wget
    runs-on: ubuntu-latest
    steps:
      - name: wget request
        run: wget https://api.mike.chiraghosh.me/script/hearings